//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissionEditor {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\ProjectResource\\autoconfig\\")]
        public string ConfigFolderPath {
            get {
                return ((string)(this["ConfigFolderPath"]));
            }
            set {
                this["ConfigFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\ProjectResource\\imagesets\\")]
        public string ImageFolderPath {
            get {
                return ((string)(this["ImageFolderPath"]));
            }
            set {
                this["ImageFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("knight.gsp.item.citemattr.xml")]
        public string ItemAttrName {
            get {
                return ((string)(this["ItemAttrName"]));
            }
            set {
                this["ItemAttrName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("knight.gsp.npc.cnpcconfig.xml")]
        public string NpcConfigFileName {
            get {
                return ((string)(this["NpcConfigFileName"]));
            }
            set {
                this["NpcConfigFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("knight.gsp.npc.cnpcshape.xml")]
        public string NpcShapeFileName {
            get {
                return ((string)(this["NpcShapeFileName"]));
            }
            set {
                this["NpcShapeFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("knight.gsp.map.cmapconfig.xml")]
        public string MapConfigFileName {
            get {
                return ((string)(this["MapConfigFileName"]));
            }
            set {
                this["MapConfigFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("roleandmonster")]
        public string HeadImageset {
            get {
                return ((string)(this["HeadImageset"]));
            }
            set {
                this["HeadImageset"] = value;
            }
        }
    }
}
